Metaswitch/chef

plugins/knife/knife-deployment-describe.rb

This pulls the keys out of the Chef databag, and uses them when communicating with HTTPS repo servers.
Fixes #140. Tested by running it and comparing to both a secure and non-secure repo, and checking that it retrieved version numbers for both.

[Reviewer: Andy] Make knife deployment describe handle secure repos

---

cookbooks/clearwater/recipes/infrastructure.rb
plugins/knife/knife-box-create.rb
plugins/knife/knife-deployment-resize.rb
plugins/knife/trigger-chef-client.rb

This fixes https://github.com/Metaswitch/chef/issues/151 (or completes the fix to https://github.com/Metaswitch/chef/issues/124, depending on how you look at it), by making Ralf nodes genuinely optional - you can remove all Ralf nodes from a deployment, or add them in to a Ralfless deployment, and /etc/clearwater/config's ralf_hostname will adjust accordingly.
It has two parts:
* code in 'knife box create' to include a ralf_hostname if it's a Ralf node or there's a --with-ralf option - which should be uncontroversial
* code in 'knife deployment resize' to spot if we've gone from having no Ralfs to having some, or vice-versa, and update /etc/clearwater/config and restart the process on Sprout/Bono/Ralf nodes to account for that.
This second part calls 'sudo monit restart all', which means …

[Reviewer: Andy] Optional Ralf

---

cookbooks/clearwater/recipes/ralf.rb
cookbooks/clearwater/recipes/sprout.rb

While testing on 14.04, I hit an issue where:
* Chronos was installed without a chronos.conf file, so bound to "localhost" by default instead of the local IP
* When clustering happened, a proper chronos.conf with the local IP is put in place - but Chronos is then SIGHUPed, which reloads the peers but doesn't rebind the HTTP stack
* Sprout then couldn't talk to Chronos
This pull request fixes that by putting a minimal chronos.conf file in place before installing Chronos. Although I hit this on 14.04 testing, I think we could hit it on 12.04 (and think this pull request is safe for 12.04), so I'd like to merge this this sprint.

[Reviewer: Ellie] Set up chronos.conf file before installing Chronos

---

plugins/knife/cluster-boxes.rb
plugins/knife/knife-deployment-resize.rb
plugins/knife/trigger-chef-client.rb

@mirw, @rkd-msw I have made the following change to resolve the merge conflict that came in with the Astaire work. This change re-instates the `update_ralf_hostname` method, and refactors the code in `cluster-boxes.rb` so that there is only one copy of `trigger_chef_client`. 
Please can you both take a look and let me have any feedback by 4pm today?
I have tested this live, by running `knife deployment resize -E dogfood -V` (i.e. without changing any counts). The resize command passed without errors and the dogfood deployment now has a `ralf_hostname` set in `/etc/clearwater/config`.

Reinstate update_ralf_hostname, and remove duplicate trigger_chef_client

---

plugins/knife/dns-records.rb
plugins/knife/knife-deployment-describe.rb

This PR contains the following fixes:
* Add astaire to `knife deployment describe`. Tested by running the command and checking the output.
* Change knife to update existing DNS records where possible instead of deleting and recreating (this fixes a window condition where requesting the record before it has been recreated can cause mass call failures). Tested by doing scaling operations and checking the DNS records were updated correctly.

[Reviewer: Andy] Scale-up/down fixes

---

cookbooks/clearwater/recipes/infrastructure.rb
cookbooks/clearwater/templates/default/config.erb

Note that this is a change from the pre-etcd Chef GR model - that set up two separate Chef
deployments, linked them together, and required clearwater-secure-connections to set up IPSec
tunnels between them. This sets up a single Chef deployment, but if the environment contains "gr =>
true", then odd-numbered and even-numbered nodes will form two separate logical "sites".
This allows testing GR function without the hassle of a NAT between sites, and I think it's simpler to use (and to code).

[Reviewer: Ellie]Allow GR deployments to be created with Chef

---

cookbooks/clearwater/recipes/infrastructure.rb
cookbooks/clearwater/templates/default/config.erb
plugins/knife/clearwater-dns-records.rb
plugins/knife/dns-records.rb

This fixes up DNS/GR stuff so that:
* Bono always uses SRV records to find Sprout
* In GR, alternate Bonos prefer different sites
* In GR, Sprout nodes only use site-local Homestead/Homer/Ralf nodes
* (In GR, your single Ellis node will only use the first site's Homer/Homestead nodes - that's probably acceptable).
I've tested by spinning up and making a basic call through a GR deployment and a non-GR deployment (checking cluster_settings in each case to check GR was as expected), and also spun up a single Sprout node to verify we don't crash if we don't have an index.

[Reviewer: Ellie] GR DNS

---

cookbooks/clearwater/recipes/config-manager.rb

Recipe is defined in the shared_config branch (PR at https://github.com/Metaswitch/chef/pull/185)

[No reviewer] Add dummy recipe for config-manager

---

cookbooks/clearwater/recipes/ellis.rb
cookbooks/clearwater/recipes/shared_config.rb
plugins/knife/knife-deployment-resize.rb

Fixes:
* We don't wait for etcd to come up before uploading shared config
* We don't apply shared config on `sprout-1` (or `sprout-2` in GR deployments)
* We create very bogus numbers in ellis's database

Reviewer Ellie - Various etcd fixes

---

cookbooks/clearwater/recipes/infrastructure.rb

AIO chef can't install because it has an undefined 'hss' variable.

[No reviewer] Set hss

---

plugins/knife/boxes.rb

This spins up 14.04 VMs in EC2.
I've explicitly tested spinning up in us-east-1, and all the other entries are taken from the trusty/amd64/ebs entries on http://cloud-images.ubuntu.com/locator/ec2/.

[Reviewer: Ellie] Update AMI IDs for Trusty

---

VPC-SUPPORT.md
plugins/knife/boxes.rb
plugins/knife/knife-security-groups-create.rb
plugins/knife/knife-security-groups-delete.rb
plugins/knife/security-groups.rb
plugins/knife/trigger-chef-client.rb

This adds support for deploying into a given subnet in a given VPC.  I'll write a README extension to describe what needs to be done to actually make use of this but the gist is:
* Set up a VPC and subnet
* Add `vpc: { vpc_id: "...", subnet_id: "..." }` to your environment file
* `knife deployment resize -E <env>`
Tested by creating/destroying deployments in a VPC and non-VPC (to check I've not broken anything in that case).

Reviewer Rob - VPC support

---

plugins/knife/dns-records.rb
plugins/knife/knife-deployment-resize.rb

This:
* sleeps for 200ms after each DNS request, to comply with the 5 req/sec limit (http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html), fixing https://github.com/Metaswitch/chef/issues/179
* sleeps for 90 seconds before updating DNS on scale-up, mitigating https://github.com/Metaswitch/chef/issues/176
I haven't tested (but I don't often do the sort of testing that hits either problem).

[Reviewer: Matt] Add in sleep statements for DNS

---

plugins/knife/clearwater-dns-records.rb

Using IP addresses in SRV records caused interop issues, so I've switched to the equivalent A record. Tested live.

[Reviewer: Andy] Use hostnames, not IP addresses, in SRV records

---

plugins/knife/boxes.rb

As discussed, we were not setting the security group for new nodes in non-VPC deployments.  This now sets them regardless.
You have volunteered to test.

Reviewer Matt - Set security group ID in non-VPC deployments

---

Gemfile.lock
plugins/knife/boxes.rb
plugins/knife/security-groups.rb

Adds support for the newest EC2 region by taking a new `fog` version.  Also makes sure that we always know what region we're working in in case API calls are made in an unusual order.
Tested by spinning up a deployment in Frankfurt from scratch (SGs, instances, chef-client, DNS records, destruction).

Reviewer Alex - Support UE central 1 (Frankfurt)

---

plugins/knife/knife-deployment-resize.rb
plugins/knife/knife-shared-config-update.rb
plugins/knife/trigger-chef-client.rb

Andy, can you review this change to add a 'knife shared config update' command that uploads shared config from the sprout-1's, and applies it to all nodes. 
Fixes #208

[Reviewer: Andy] Add in shared config control

---

cookbooks/clearwater/templates/default/shared_config.erb
plugins/knife/boxes.rb

Minor chef fixes to not set the node_index in shared config and to use the right commands to unmonitor the cluster/config-manager.

[Reviewer: Rob] Minor chef fixes

---

plugins/knife/boxes.rb
roles/clearwater-base.rb

This adds a base role that just installs the local config, sets up security/certificates and installs clearwater-infrastructure. This is useful when creating a blank box for testing.

[Reviewer: Rob] Add base role

---

cookbooks/clearwater/recipes/alarms.rb
cookbooks/clearwater/recipes/infrastructure.rb
roles/alarms.rb
roles/bono.rb
roles/clearwater-config-manager.rb
roles/clearwater-etcd.rb
roles/cw_aio.rb
roles/homestead.rb
roles/memento.rb
roles/ralf.rb
roles/sprout.rb

Split out alarms into a separate role. (We may want to convert this to a dependency later, but this stops chef installs failing)
Fixes #222 and https://github.com/Metaswitch/clearwater-snmp-handlers/issues/85

[Reviewer: Matt] Add alarms role

---

cookbooks/clearwater/recipes/shared_config.rb
plugins/knife/trigger-chef-client.rb

Rob, can you review this change to check that etcd is functional before trying to upload shared config. I've also taken out some code that suppressed logs - this isn't useful anymore as the etcd scripts are no longer massively spammy (they were also hiding useful logs). 
Fixes #204, and makes the chef install significantly more reliable

[Reviewer: Rob] Check etcd is functional

---

roles/cw_aio.rb

swap recipie[clearwater::cw_aio] and role[alarms], to avoid dependency problems with snmpd

No reviewer

---

plugins/knife/knife-security-groups-delete.rb

Hi Rob,
Please can you review this fix to the knife security groups delete command? This matches knife-security-groups-create.rb. I was seeing the following:
```
/home/ubuntu/chef/.chef/plugins/knife/clearwater-security-groups.rb:290:in `clearwater_security_groups': wrong number of arguments (0 for 1) (ArgumentError)
```

Reviewer RKD: Fix knife security groups delete

---

cookbooks/clearwater/recipes/shared_config.rb

If we're installing the shared config role then we need clearwater-etcd, so make sure it's installed.

[Reviewer: Graeme] Install clearwater-management

---

plugins/knife/dns-records.rb

Sleep after querying record, rather than after modifying, to properly comply with route53 rate limit.
fixes #179

Sleep after querying record - No Reviewer

---

cookbooks/clearwater/templates/default/shared_config.erb

We usually set scscf_uri up with a semicolon (`sip:sprout.rkd.cw-ngv.com;transport=tcp`). If we don't quote it in the shared config, that gets lost:
`scscf_uri=sip:sprout.rkd.cw-ngv.com;transport=tcp`
is treated as:
```
scscf_uri=sip:sprout.rkd.cw-ngv.com
transport=tcp
```
With this, we'd have spotted https://github.com/Metaswitch/homestead/issues/263 earlier.

[Reviewer: Ellie] Quote the scscf_uri parameter

---

roles/bono.rb
roles/call-diversion-as.rb
roles/clearwater-base.rb
roles/clearwater-config-manager.rb
roles/clearwater-etcd.rb
roles/ellis.rb
roles/homer.rb
roles/homestead.rb
roles/local_config.rb
roles/mangelwurzel.rb
roles/memento.rb
roles/ralf.rb
roles/seagull.rb
roles/sipp.rb
roles/sprout.rb

Adds local_config role.
Migrates roles to clearwater-etcd rather than config-manager.
Shifts where alarms role is run.
These changes shouldn't cause any issues with back-compatibility.

Piecemeal install updates

---

plugins/knife/knife-box-list.rb

Not quite as clean as it could be, but `find_nodes` doesn't give me the fine-grained control I'd like to express "(roles:chef-base OR roles:cw_aio)" and I can't see a nice way to extend it.

[Reviewer: Andy] Include AIO nodes in knife box list output

---

plugins/knife/knife-deployment-resize.rb

Forgot I hadn't sent this out for review. We sleep for 100 seconds near the end of `knife deployment resize` - this moves more of that 100 seconds to be before creating numbers in Ellis, to reduce the risk of it happening before we get shared config.

[Reviewer: Alex] Move sleep around to give Ellis the best chance of creating numbers

---

plugins/knife/dns-records.rb

Sleep when deleting DNS records so we don't hit the AWS limit. I've also increased the time for creating and modifying records as I've been seeing rate limit errors on these as well
Fixes #268

[Reviewer: Rob] Sleep for longer when changing DNS addresses

---

plugins/knife/clearwater-dns-records.rb

sprout_hostname is set to sprout.domain (and used by, for example, Homestead nodes) so there should be a DNS record for it.
Not merging until the release is cut.

[Reviewer EM] [DO NOT MERGE] Add sprout.domain DNS records

---

docs/knife_commands.md
plugins/knife/knife-deployment-resize.rb

This PR adds support for an easy way to spin up a deployment with I-CSCF disabled.
Part of enabling I-CSCF function by default.

[Reviewer: Rob] Add option to spin up S-CSCF only deployment

---

plugins/knife/knife-box-create.rb

Fixes #278 - I'll also add a note to http://docs.projectclearwater.org/en/stable/Creating_a_deployment_with_Chef.html#creating-an-all-in-one-aio-node.
I've tested:
```
...
Environment: rkd
Run List: role[cw_aio]
JSON Attributes: {:clearwater=>{:seagull=>nil, :ralf=>false}}
Note: The signup code for AIO nodes is 'secret', not the value configured in knife.rb
```

[Reviewer: Alex] Print a note about the AIO signup key

---

plugins/knife/dns-records.rb

This resolves some problems we've been seeing with throttling on Route 53.
The all! call in fog-aws causes us to request all the records in the zone. This works by repeatedly requesting a page of records at a time, where with a large zone causes a large number of pages to be requested. It's also not concurrently safe as a change may be made between pages being requested.
This resolves this by using the correct call on fog, which allows us to ask for the record we actually want instead of all of the records, which makes it much quicker, and hugely reduces the number of requests required.
This call has been in fog-aws since at least 0.6.0, so we don't need to upgrade fog-aws - see https://github.com/fog/fog-aws/blob/v0.6.0/lib/fog/aws/models/dns/records.rb#L67-L104

[Reviewer: EM] Only request the record we want instead of all!

---

cookbooks/clearwater/recipes/database.rb
cookbooks/clearwater/recipes/homer.rb
cookbooks/clearwater/recipes/homestead.rb

***This PR is currently based against the split-storage-packages branch - if that branch has already been merged into dev this branch should also be merged into dev***
A few fixes that I think we need.
* I think the database node should install the homestead-prov schema. We don't install it by default (i.e. it's not a dependency of atlas-node) because we don't want it if we're running with an HSS, but generally when we're using chef we don't have an HSS and there is no harm in installing it.
* The homer recipe should now install homer-node.
* The homestead recipe shouldn't install homestead-node-prov because that isn't a thing.

Reviewer AJL: Split storage fixes post-Cassandra schema testing

---

cookbooks/clearwater/recipes/homer.rb
cookbooks/clearwater/recipes/memento.rb
cookbooks/clearwater/recipes/vellum.rb
cookbooks/clearwater/templates/default/shared_config.erb

Use the appropriate packages for Homer/Memento depending on whether we are in split-storage or not.
Install the homer-cassandra and memento-cassandra packages onto the Vellum node (homested-prov-cassandra is already installed by the debian dependencies).
Tested that this spins up a working split-storage deployment, with passing live tests.

[Reviewer: RKD] Homestead-prov, Homer and Memento split-storage

---

plugins/knife/knife-security-groups-delete.rb

This change means that if you delete security groups after pulling the new Chef code, it'll work, so you don't have to make sure to run `knife security groups delete` before a `git pull` - this feels cleaner.

[Reviewer: Sathiyan] Clean out historical security groups

---

plugins/knife/knife-deployment-utils.rb

So that we don't hit the API request limit when creating large deployments.
Created a 25 VM deployment and it worked.

[Reviewer: RKD] Scale sleep based on number of threads

---

cookbooks/clearwater/recipes/shared_config.rb
cookbooks/clearwater/templates/default/shared_config.erb
plugins/knife/clearwater-security-groups.rb

Please can you review this chef change to expose the new management APIs. I've tested this live by checking:
* I can query the list of IMPUs from a sprout node using `$hs_mgmt_hostname`. 
* I can query a subscriber's bindings from a homestead node using `$sprout_mgmt_hostname`.

[Reviewer: Graeme] Expose the homestead and sprout management APIs

---

cookbooks/clearwater/templates/default/shared_config.erb

Add a default billing realm value if nothing has been set. This value can still be overridden in the environment file, and doesn't change anything if there are no Ralfs in the deployment.
Tested live

[Reviewer: Adam] Add default billing realm value

---

cookbooks/clearwater/recipes/chronos.rb
cookbooks/clearwater/templates/default/chronos_gr.conf.erb
plugins/knife/clearwater-dns-records.rb

This adds the Chronos GR template and DNS records. Tested by spinning up GR and non-GR deployments and checking they both basically worked.
Once this is merged, I'll merge the split-clusters branch into dev entirely.

[Reviewer: Sathiyan] Add chronos gr template

---

plugins/knife/knife-deployment-resize.rb

If we aren't using split storage, we need to initialize the dime and vellum  counts to their current values so that the hashes match.
Otherwise we have:
{:bono=>1, :ellis=>1, :ibcf=>0, :homer=>1, :homestead=>1, :sprout=>1, :sipp=>0, :ralf=>0, :seagull=>0, :vellum=>0, :dime=>0}
compared against
{:ellis=>1, :bono=>1, :homestead=>1, :ralf=>0, :homer=>1, :sprout=>1, :ibcf=>0, :sipp=>0, :seagull=>0}
which doesn't match, which causes it to print the following pointless confirmation prompt:
```
$ knife deployment resize -E environment
Continue? (y/N)
```

[Reviewer: Ellie] Prevent erroneous confirmation on resize

---

cookbooks/clearwater/recipes/shared_config.rb

Stops us from running upload_blah.json on sprout nodes, as the plugins now create and upload default template files if none are already preset.
We still want to run upload shared config though, so that deployments come up alive and running.

[No Reviewer] Do not run sprout-only upload scripts on startup

---

docs/knife_commands.md

Per Ellie's request, I have added a short section to knife_commands.md on connection errors that can occur with rogue references to clients/nodes that no longer exist, after hitting these problems yesterday.
Ellie, please let me know if this is okay or if you'd like any changes. Thanks!

Update to knife commands documentation with connection error troubleshooting

---

cookbooks/clearwater/recipes/homer.rb
cookbooks/clearwater/recipes/homestead.rb

Fix the do_backup commands so that they do run in the signaling namespace

[Reviewer: Seb] Add signaling command to backups

---

cookbooks/clearwater/recipes/shared_config.rb
plugins/knife/knife-deployment-utils.rb

Some small changes to chef for a non-GR deployment:
- don't set chronos_hostname, sprout_impi_store or cassandra_hostname if not
using split-storage (just use the defaults)
- fix error when trying to deploy ralf
Tested that it spins up a new-style deployment correctly and live tests pass against it

[Reviewer: Adam] split-clusters fixes

---

plugins/knife/dns-records.rb

Ellie,
We've seen rate limits being hit when deleting DNS records. To prevent this, I've tweaked the sleep timers between AWS DNS operations:
- I've added a sleep when performing a find request (as this is hitting AWS, and thus may cause later requests to throttle).
- I've increased the sleep when modifying a record
- I've changed the deletion sleep so that it only applies when we actually hit AWS, and increased it.

[Reviewer: EM] Adjust sleep times when changing DNS

---

plugins/knife/knife-box-create.rb
plugins/knife/knife-box-delete.rb
plugins/knife/knife-deployment-delete.rb
plugins/knife/knife-deployment-utils.rb

Ellie,
We want to allow `knife box delete -y` to work, despite the comment in the code.
It's really useful to allow us to automate various processes.

[Reviewer: Ellie] Allow knife box delete -y to work

---

plugins/knife/knife-clearwater-utils.rb

The expand_hashes function would previously silently fail when passed an argument of the wrong form. Passing, for example, "cedar" rather than the proper form "cedar-site1" would cause the site parameter to be set to zero by casting 'nil' to an integer. This led to some problems in diagnosing a related issue.
This fix will make the expand_hashes function throw an exception when its argument is not of the correct form.

[Reviewer: EM] Improve expand_hashes function

---

cookbooks/clearwater/recipes/shared_config.rb

This fixes up the chef recipe  for `shared_config` so that it uses the new `cw-config` script. I've tested this and it works provided we make a small fix to cw-config at the same time (covered by a separate pull request.

[Reviewer: SS5] Fixing broken chef recipe for shared_config

---

plugins/knife/knife-deployment-describe.rb

Seb,
This fixes knife deployment describe:
- We now describe the version of rogers (as a result of https://github.com/Metaswitch/astaire/pull/93)
- Sprout no longer has Chronos and Astaire (this is a result of the split storage changes)
- I've improved a log line so that you get
```
Packages on rjw2-sprout-1:
sprout                         1.0-171019.160039
sprout-libs                    1.0-171019.160039
No package version found for memento
```
instead of just `No package version found` for each package not found.

[Reviewer: Seb] Update knife deployment describe

---

plugins/knife/boxes.rb

Fixes a bug that chef wasn't able to quiesce box succeessfullly. 
Live tested by:
1. make change to  chef submodule in chef-private
2. create deployment with three Vellums
3. resize to two Vellums and see the operation succeeded

Unmonitor group for killing box

---

cookbooks/clearwater/recipes/shared_config.rb

This is a temporary workaround for problems we've seen in how this interacts with shared config infrastructure changes. Should be removed once it's sorted.

Pause to avoid config change race

---

cookbooks/clearwater/recipes/shared_config.rb
cookbooks/clearwater/templates/default/sas.json.erb
cookbooks/clearwater/templates/default/shared_config.erb

Make Chef configure SAS using the new sas.json config file rather than the option in shared_config.

Allow Chef to setup new SAS configuration

---

plugins/knife/security-groups.rb

When creating security groups, you will encounter a "RequestLimitExceeded" error when assigning them to instances too fast. This limit is fundamental to AWS hence cannot be bypassed without limiting the speed in-solution. Hence, I have added a 1 second sleep to prevent this error from occurring.

sleep to bypass request limit
