Metaswitch/chef

cookbooks/clearwater/templates/default/cluster/chronos.conf.erb
Update to set the chronos address - needed as part of https://github.com/Metaswitch/chronos/pull/99/files
=> [Reviewer: Rob] Update chronos address

plugins/knife/cluster-boxes.rb, plugins/knife/knife-deployment-resize.rb
Andy,
Please can you review my enhancement to chef to support Astaire and use it to do one-shot scale-up/down.  The old two-phase scale-up/down is still supported.
I've live tested (as you've seen).
Matt
=> [Reviewer: Andy] Enhance Chef to do one-shot scale-up

cookbooks/clearwater/templates/default/config.erb, environments/template.rb
Graeme,
Please can you review this enhancement for stress testing - allow chef to set billing_realm.  I've live-tested, and I don't think there are any environment docs beyond pointing users at the template.
Thanks,
Matt
=> [Reviewer: Graeme] Allow chef to set billing_realm

cookbooks/clearwater/recipes/etcd.rb, roles/bono.rb, roles/clearwater-etcd.rb, roles/ellis.rb, roles/homer.rb, roles/homestead.rb, roles/mangelwurzel.rb, roles/ralf.rb, roles/sprout.rb
Adding etcd roles now as these are used by the chef server
=> [No reviewer] etcd roles

README.md
Update README links to point at readthedocs. Untested!
=> Reviewer RKD: Update links in README to point at readthedocs

cookbooks/clearwater/recipes/infrastructure.rb, plugins/knife/boxes.rb, plugins/knife/clearwater-security-groups.rb, plugins/knife/knife-deployment-resize.rb
Hi Ellie,
I've reviewed https://github.com/Metaswitch/chef/pull/168/files and I'm happy with it, other than the fixes below - if you're happy with these then I'll merge them into your branch and then you can do what you like with your branch.
Cheers,
Graeme
=> Reviewer EM: Live test fixes

plugins/knife/boxes.rb
Unmonitor clearwater-etcd and clearwater-cluster-manager before decommissioning. Hoping to merge into your etc_cluster branch.
=> Reviewer EM: Final fix

cookbooks/clearwater/recipes/cluster.rb, plugins/knife/boxes.rb
Metaswitch/clearwater-monit#16
=> {No reviewer] Add in groups

cookbooks/clearwater/recipes/infrastructure.rb
Don't assume there's an index as this breaks box create
=> [Reviewer: Rob] Don't assume there's an index

plugins/knife/dns-records.rb
Fixes #180.
Simple fix, I thought it better to pass the options in to get the good diagnostics, rather than make the diags worse.
=> Reviewer Matt - Pass options through to error handling

cookbooks/clearwater/recipes/etcd.rb
Use clearwater-management instead of separate packages
=> [Reviewer: Andy] Use overall package instead

cookbooks/clearwater/recipes/cluster-manager.rb, roles/bono.rb, roles/clearwater-cluster-manager.rb, roles/ellis.rb, roles/homer.rb, roles/homestead.rb, roles/mangelwurzel.rb, roles/ralf.rb
Move bono/ellis to just install clearwater-cluster-manager
=> [Reviewer: Andy] Add in cluster role

cookbooks/clearwater/recipes/config-manager.rb, roles/bono.rb, roles/clearwater-config-manager.rb, roles/ellis.rb
=> [No reviewer] Cluster manager role

cookbooks/clearwater/recipes/ralf.rb, cookbooks/clearwater/recipes/shared_config.rb, cookbooks/clearwater/recipes/sprout.rb, cookbooks/clearwater/templates/default/chronos.conf.erb, cookbooks/clearwater/templates/default/cluster/cluster_settings.erb, cookbooks/clearwater/templates/default/cluster/remote_cluster_settings.erb, cookbooks/clearwater/templates/default/config.erb
This removes the Chronos set up from Chef.
=> [Reviewer: Andy] No need to explicitly install chronos

plugins/knife/knife-deployment-describe.rb
Fixes #152. I've updated our databag and confirmed that 'knife deployment describe' works.
=> [Reviewer: Andy] Don't mollycoddle invalid PEM in databags

plugins/knife/knife-cacti-update.rb
Fixes #211. I've tested and confirmed that we no longer bail out on the first failure.
=> [Reviewer: Andy] Add /bin/true to the end of commands

cookbooks/clearwater/files/default/cacti/templates/cacti_host_template_sprout.xml
Added to xml for overload statistics
=> [Reviewer: Matt] - Added graphs to xml for overload statistics

cookbooks/clearwater/recipes/infrastructure.rb, cookbooks/clearwater/recipes/local_config.rb, plugins/knife/boxes.rb, plugins/knife/knife-box-create.rb, plugins/knife/knife-clearwater-utils.rb, plugins/knife/knife-deployment-resize.rb, plugins/knife/knife-deployment-utils.rb, roles/bono.rb, roles/ellis.rb, roles/homer.rb, roles/homestead.rb, roles/mangelwurzel.rb, roles/ralf.rb, roles/seagull.rb, roles/sprout.rb
Rob, can you review this change to refactor the deployment resize commands. The main changes are to add a deployment utils module that holds the utility functions for the deployment class, and to make creating the local config a recipe in its own right
=> [Reviewer: Rob] Refactor out deployment resize function

cookbooks/clearwater/recipes/homestead.rb
=> [Reviewer: Ellie] Install clearwater-prov-tools alongside homestead-prov

cookbooks/clearwater/templates/default/openimscorehss/debian.preseed.erb
Rob,
Please can you review this (fixes #223)?  Tested live.  I've fixed up other parameters even if they weren't affected by this bug.
Thanks,
Matt
=> [Reviewer: Rob] Strip superfluous whitespace in HSS configuration

plugins/knife/knife-box-create.rb
This adds a --standalone option to knife box create, which allows single boxes to be created with valid config. 
Fixes #195 
Tested live
=> [Reviewer: Rob] Add standalone option

cookbooks/clearwater/recipes/security.rb, cookbooks/clearwater/templates/default/apt.keys.erb, cookbooks/clearwater/templates/default/apt.list.erb, environments/template.rb
Hi Andy,
Please can you review this change to allow multiple repo servers to be specified in an environment? Please can you review it fairly carefully (even though you wrote most of it). I've got an email to send out when I merge it, and I'll also update the big environments.
Graeme
=> Reviewer AMC: Allow multiple repos

README.md, docs/knife_commands.md
Rob, can you please review this documentation for chef?
=> [Reviewer: Rob] Add in knife commands doc

plugins/knife/knife-deployment-resize.rb
Workaround for https://github.com/Metaswitch/chef/issues/246
=> [Reviewer: Alex] Add in sleep for Ellis

cookbooks/clearwater/files/default/cacti/templates/cacti_host_template_homestead.xml, cookbooks/clearwater/files/default/cacti/templates/cacti_host_template_sprout.xml
Host templates pulled from cacti for the new REG SUB and BIND stats on sprout, and for updated CDEF functions in Sprout and Homestead data templates
=> [No Reviewer] Graph template updates for new stats

cookbooks/clearwater/recipes/shared_config.rb, cookbooks/clearwater/templates/default/shared_config.erb, cookbooks/clearwater/templates/default/sprout/s-cscf.erb, plugins/knife/clearwater-dns-records.rb
Rob, can you review the chef changes for the new sproutlet configuration
=> [Reviewer: Rob] Set up new sprout config in chef

cookbooks/clearwater/recipes/shared_config.rb, cookbooks/clearwater/templates/default/shared_config.erb, plugins/knife/clearwater-dns-records.rb, roles/sprout.rb
=> [No reviewer] Sprout config

cookbooks/clearwater/recipes/shared_config.rb, cookbooks/clearwater/templates/default/shared_config.erb
I think this is slightly more elegant than your suggestion
=> Reviewer EM: Pass enum server through as given

cookbooks/clearwater/recipes/shared_config.rb
Fix up alias list for GR deployments
=> [No reviewer] Fix up alias list for GR deployments

cookbooks/clearwater/recipes/local_config.rb, cookbooks/clearwater/recipes/shared_config.rb, cookbooks/clearwater/templates/default/shared_config.erb, plugins/knife/clearwater-dns-records.rb
Fix local and shared config for N-Site GR.  Also fix DNS records.
=> [Reviewer: GDR] Fixes for N-Site GR

cookbooks/clearwater/recipes/cw_aio.rb
Co-req change to https://github.com/Metaswitch/clearwater-infrastructure/pull/353
=> [No review required] Pass new arguments into clearwater-aio-install.sh

roles/chef-base.rb
I'll send out an announcement before merging.
=> [Reviewer: Ellie] Don't use config in the roles

cookbooks/clearwater/recipes/database.rb, cookbooks/clearwater/recipes/database_local_config.rb, cookbooks/clearwater/recipes/local_config.rb, cookbooks/clearwater/recipes/shared_config.rb, cookbooks/clearwater/templates/default/database_local_config.erb, cookbooks/clearwater/templates/default/local_config.erb, cookbooks/clearwater/templates/default/shared_config.erb, plugins/knife/boxes.rb, plugins/knife/clearwater-dns-records.rb, plugins/knife/clearwater-security-groups.rb, plugins/knife/knife-deployment-describe.rb, plugins/knife/knife-deployment-resize.rb, plugins/knife/knife-deployment-utils.rb, roles/database.rb, roles/database_local_config.rb, roles/ralfstead.rb
It may be best for you to have a glance over it all, and then I can tell you why i did each bit as i did, or if it would fit you better I could add line notes where there are notable changes? 
Let me know how you want to go about handling this.
=> [Reviewer: Ellie] Big PR of split-storage changes

docs/knife_commands.md
Add a little bit of cookbook troubleshooting to the docs
=> [Reviewer: Adam] Add troubleshooting help for cookbook errors

cookbooks/clearwater/recipes/bono.rb, cookbooks/clearwater/recipes/database.rb, cookbooks/clearwater/recipes/dime.rb, cookbooks/clearwater/recipes/homestead.rb, cookbooks/clearwater/recipes/ralf.rb, cookbooks/clearwater/recipes/ralfstead.rb, cookbooks/clearwater/recipes/shared_config.rb, cookbooks/clearwater/recipes/sprout.rb, cookbooks/clearwater/recipes/vellum.rb, cookbooks/clearwater/recipes/vellum_local_config.rb, cookbooks/clearwater/templates/default/shared_config.erb, cookbooks/clearwater/templates/default/vellum_local_config.erb, plugins/knife/boxes.rb, plugins/knife/clearwater-dns-records.rb, plugins/knife/clearwater-security-groups.rb, plugins/knife/knife-deployment-describe.rb, plugins/knife/knife-deployment-resize.rb, roles/dime.rb, roles/ralfstead.rb, roles/vellum.rb, roles/vellum_local_config.rb
Updating to fit in line with other package name changes
=> [No Reviewer] split package names

docs/knife_commands.md
Add bulk delete commands when tidying up chef references
=> [No reviewer] Add bulk delete commands

plugins/knife/knife-cacti-update.rb
Add Homestead to the set of nodes that's included in cacti update
=> [Reviewer: Adam] Add Homestead graphs to cacti update command

Gemfile, Gemfile.lock, plugins/knife/boxes.rb
I think one of the Edinburgh teams tested this at the time I wrote it and confirmed it worked (but I forgot to merge it).
Note that I needed to pull in a newer fog-aws gem to be able to use the VPC-related methods.
=> [Reviewer: Ellie] Check if we have a default VPC, and use VPC images if so

docs/knife_commands.md
Minor docs change following PR #313
=> [Reviewer=Ellie] Add bullet describing new environment variable

plugins/knife/clearwater-security-groups.rb
Open up the ports required for BGCF testing.
=> Open ports for BGCF

plugins/knife/clearwater-security-groups.rb
Adds three new port ranges to SIPP nodes to cover the ports used by the new live tests.
=> [Reviewer: HJS] More sipp ports

cookbooks/clearwater/recipes/shared_config.rb, cookbooks/clearwater/templates/default/shared_config.erb
Sets up homestead_impu_store in the same was as sprout_registration_store
=> [Reviewer: Richard] Add homestead_impu_store option

plugins/knife/knife-deployment-resize.rb, plugins/knife/knife-deployment-utils.rb
Ellie,
Two minor changes for Chef:
- Create the security groups after confirmation. This prevents you having to wait a while before getting a Y/N prompt.
- Add more logging, including logging exceptions at info level. This means you can actually debug what's going on, without having to provide `-VV` which causes all the SSH traffic to be logged.
=> [Reviewer: Ellie] Minor fixes for Chef

cookbooks/clearwater/recipes/shared_config.rb
I've live tested this and it works! Please can you review?
=> [Reviewer: SS5] Moving etcd polling to top of shared_config recipe
